audio:
  sampling_rate: 22050
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  n_mels: 80
max_lengths:
  phone: 384
  frame: 512
measures:
  silence_mask: False
diffusion:
  num_steps: 1000
  beta_0: 0.000001
  beta_T: 0.01
  step_embed_dim_in: 128
  step_embed_dim_out: 512
  step_embed_dim_hidden: 512
meta: [duration, mel, audio, energy, pitch, srmr, snr]
consistency:
  noise_factor: 0.1
  measure_nlayers: 4
  dvector_nlayers: 2
  in_channels: 80
  filter_size: 256
  kernel_size: 3
  dropout: 0.1
  depthwise: True
  measures: [energy, pitch, srmr, snr]
  dvector_dim: 256
evaluation:
  num_steps: 8
  num_workers: 96
  chunk_size: 128
  save_audio: False
  batch_size: 64