audio:
  sampling_rate: 22050
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  n_mels: 80
max_lengths:
  phone: 448
  frame: 576
  vocoder: 64
diffusion_vocoder:
  T: 200
  beta_0: 0.0001
  beta_T: 0.02
  step_embed_dim_in: 128
  step_embed_dim_out: 512
  step_embed_dim_hidden: 512
  residual_channels: 64
  residual_layers: 30
  dilation_cycle_length: 10