audio:
  sampling_rate: 22050
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  n_mels: 80
max_lengths:
  phone: 384
  frame: 512
  vocoder: 64
measures:
  silence_mask: False
diffusion_vocoder:
  T: 1000
  beta_0: 0.000001
  beta_T: 0.01
  step_embed_dim_in: 128
  step_embed_dim_out: 512
  step_embed_dim_hidden: 512
  residual_channels: 64
  residual_layers: 30
  dilation_cycle_length: 10
  learnable_mel: False
meta: [duration, mel, audio, energy, pitch, srmr, snr]
consistency:
  nlayers: 6
  in_channels: 80
  filter_size: 256
  kernel_size: 3
  dropout: 0.1
  depthwise: True
  transformer_layers: 4
  measures: [energy, pitch, srmr, snr]
  dvector_dim: 256
evaluation:
  sampling_T: 4
  num_workers: 96
  chunk_size: 128
  save_audio: False
  batch_size: 64